### PR TITLE
feat: main functionality

### PR DESCRIPTION
**Pull request by DudaGod**

### CODE REVIEW

**Comment by unlok** [comment]
Why not TS? Why without tests?

**Comment by DudaGod** [comment]
> Why not TS? Why without tests?

Because I wrote it on my knees and didn't want to spend a lot of time on it.
The purpose of this plugin is to show the guys from the neighboring team that their problem can be solved using plugin to hermione.

**Comment by unlok** [comment]
> > Why not TS? Why without tests?
> 
> Because I wrote it on my knees and didn't want to spend a lot of time on it.
> The purpose of this plugin is to show the guys from the neighboring team that their problem can be solved using plugin to hermione.

Ah, got it. So, are we going to remove this repo after some time?

**Comment by DudaGod** [comment]
> Ah, got it. So, are we going to remove this repo after some time?

No. Most likely they will use it when migrating to hermione.

**Pull request merged**
